spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://keycloak:8090/realms/ca-connect/protocol/openid-connect/certs}
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**

            - id: profile-service
              uri: lb://PROFILE-SERVICE
              predicates:
                - Path=/api/profiles/**

            - id: location-service
              uri: lb://LOCATION-SERVICE
              predicates:
                - Path=/api/locations/**

            - id: messaging-service
              uri: lb://MESSAGING-SERVICE
              predicates:
                - Path=/api/messages/**

            - id: messaging-service-ws
              uri: lb://MESSAGING-SERVICE
              predicates:
                - Path=/ws/**

# eureka configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
    fetch-registry: ${EUREKA_CLIENT_FETCHREGISTRY:true}
    register-with-eureka: ${EUREKA_CLIENT_REGISTERWITHEUREKA:true}

# server port
server:
  port: ${SERVER_PORT:8080}