apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtc2VydmljZTo1NDMyL2NhX2Nvbm5lY3RfZGI=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: QWxiaW5yZWppQDMw
  POSTGRES_DB: Y2FfY29ubmVjdF9kYg==   
  GEO_CAGE_API_KEY: ZDE0YzQ1ZDdiNzg0NDAwNThlZGIxYmU1ZWVjZTFlNTc=