spring:
  application:
    name: location-service

#  db connection
  datasource:
    url: ${SUPERBASE_DB_URL}
    username: postgres
    password: ${SUPERBASE_DB_PASSWORD}
    
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect


# eureka client config
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone:  ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

# port configuration
server:
  port: 8082